"""initial schema

Revision ID: 042ffd96435b
Revises:
Create Date: 2026-09-12 13:10:29.009911
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "042ffd96435b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("taint_level", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "benchmark_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("config_name", sa.String(length=64), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policies",
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("yaml_source", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "benchmark_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("attack_succeeded", sa.Boolean(), nullable=False),
        sa.Column("task_completed", sa.Boolean(), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["benchmark_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_benchmark_results_run_id"), "benchmark_results", ["run_id"], unique=False
    )
    op.create_table(
        "screening_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("trust_label", sa.String(length=16), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("content_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detector_outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["policy_version"],
            ["policies.version"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("row_hash"),
    )
    op.create_index(
        op.f("ix_screening_events_content_sha256"),
        "screening_events",
        ["content_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_events_decision"), "screening_events", ["decision"], unique=False
    )
    op.create_index(op.f("ix_screening_events_seq"), "screening_events", ["seq"], unique=True)
    op.create_index(
        op.f("ix_screening_events_session_id"), "screening_events", ["session_id"], unique=False
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("risk_tier", sa.Integer(), nullable=False),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("execution_mode", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["screening_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(op.f("ix_tool_calls_tool_name"), "tool_calls", ["tool_name"], unique=False)
    op.create_table(
        "adjudications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tool_call_id", sa.UUID(), nullable=False),
        sa.Column("final_decision", sa.String(length=24), nullable=False),
        sa.Column("rule_fired", sa.String(length=128), nullable=False),
        sa.Column("packet_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tool_call_id"),
    )
    op.create_table(
        "adjudication_votes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("adjudication_id", sa.UUID(), nullable=False),
        sa.Column("check_name", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("model_digest", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adjudication_id"],
            ["adjudications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_adjudication_votes_adjudication_id"),
        "adjudication_votes",
        ["adjudication_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adjudication_votes_adjudication_id"), table_name="adjudication_votes")
    op.drop_table("adjudication_votes")
    op.drop_table("adjudications")
    op.drop_index(op.f("ix_tool_calls_tool_name"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_screening_events_session_id"), table_name="screening_events")
    op.drop_index(op.f("ix_screening_events_seq"), table_name="screening_events")
    op.drop_index(op.f("ix_screening_events_decision"), table_name="screening_events")
    op.drop_index(op.f("ix_screening_events_content_sha256"), table_name="screening_events")
    op.drop_table("screening_events")
    op.drop_index(op.f("ix_benchmark_results_run_id"), table_name="benchmark_results")
    op.drop_table("benchmark_results")
    op.drop_table("policies")
    op.drop_table("benchmark_runs")
    op.drop_table("agent_sessions")
    # ### end Alembic commands ###
